ci:
    skip: [uv-lock]
    
minimum_pre_commit_version: "2.9.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.17
    hooks:
      - id: uv-lock
        args: ["--directory=natural4-server", "--frozen"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
