services:
  nginx-proxy:
    image: "${CCLAW_REGISTRY}/smucclaw/nginx-router:main"
    restart: always
    ports:
      - "${LOCAL_PORT}:80"
    depends_on:
      - dsl-app
  dsl-app:
    image: ${CCLAW_REGISTRY}/smucclaw/dsl-app:main
    restart: always
    volumes:
      - type: bind
        source: /var/nl4
        target: /var/nl4
    environment:
      - NL4_WORKDIR=/var/nl4
