[tool.poetry]
name = "natural4-server"
version = "0.1.0"
description = ""
authors = ["CCLAW"]
readme = "README.org"
packages = [{include = "natural4_server"}]

[tool.poetry.dependencies]
python = "^3.11.0"
cytoolz = "^0.12.1"
Flask = "^2.3.0"
gunicorn = "^20.1.0"
pyrsistent = "^0.19.3"
pyrsistent-extras = "^0.1.0"
pyvis = {version = "^0.3.2", optional = true}
maude = {version = "^1.2.2", optional = true}
umaudemc = {version = "^0.12.1", optional = true}
networkx = {version = "^3.0", optional = true}

[tool.poetry.dev-dependencies]
ipdb = "*"

[tool.poetry.extras]
formal_verification = ["maude", "umaudemc", "pyvis", "networkx"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
